using System.Text;
using MarkupPM.Models;

namespace MarkupPM.Services;

/// <summary>
/// Serializes a Proyecto to Markdown. Format is stable and round-trip safe with MdParser.
/// </summary>
/// <remarks>
/// Format:
///   # {ProjectName}
///
///   ## {PhaseName}
///   <!-- phase-id: {id} -->
///
///   - [ ] {TaskName}  <!-- id:{id} prio:{prio} resp:{resp} fecha:{fecha} dep:{id1,id2} -->
///     {notes line 1}
///     {notes line 2}
/// </remarks>
public class MdSerializer : IMdSerializer
{
    private static readonly string[] EstadoToken = ["[ ]", "[~]", "[x]"];
    private static readonly string[] PrioridadToken = ["baja", "media", "alta"];

    private static readonly string[] AiHeaderLines =
    [
        "<!--",
        "MarkupPM AI instructions — complete reference for parsers and AI agents",
        "==========================================================================",
        "",
        "PURPOSE",
        "  Create or update a project plan in Markdown that can be parsed by MarkupPM",
        "  without data loss. Output only valid MarkupPM content.",
        "",
        "TOP-LEVEL STRUCTURE (required order)",
        "  1) Project title:  # {ProjectName}",
        "  2) One or more phases, each consisting of:",
        "       ## {PhaseName}",
        "       <!-- phase-id: {id} -->",
        "       zero or more task lines (with optional notes below each)",
        "",
        "TASK LINE FORMAT — exact key order is mandatory",
        "  - {state} {TaskName}  <!-- id:{id} prio:{prio} resp:{resp} fecha:{fecha} dep:{dep} -->",
        "  State tokens:  [ ] pending  |  [~] in progress  |  [x] completed",
        "  Example:",
        "    - [ ] Diseñar esquema de base de datos  <!-- id:a3f8c12e prio:alta resp:Ana_García fecha:2026-06-15 dep:b2e1d09f,c4a7f831 -->",
        "",
        "SECTION 1 — ID CONVENTIONS",
        "  - Default format generated by the app: 8 lowercase hexadecimal characters",
        "    (first 8 chars of a random UUID without hyphens), e.g. a3f8c12e.",
        "  - The parser accepts ANY non-whitespace sequence as an id.",
        "    Semantic ids are fully valid: f1, fase-diseno, T-001, REQ.3.2, PROJ-42.",
        "  - Allowed characters in ids: letters, digits, hyphens (-), underscores (_),",
        "    dots (.), and other non-whitespace printable chars. No spaces.",
        "  - When migrating from an external system with stable ids (e.g. TASK-0017,",
        "    F2.26), preserve the original ids as-is. Do not regenerate them.",
        "  - Every id must be unique across the entire file (phases and tasks share",
        "    the same namespace). Duplicate ids cause silent data corruption.",
        "",
        "SECTION 2 — FIELD VALUES AND DEFAULTS",
        "  Field     | Empty allowed? | How to write empty     | Notes",
        "  ----------|----------------|------------------------|------------------------------------",
        "  id        | NO             | —                      | Always required; must be non-empty.",
        "  prio      | NO             | —                      | Must be baja, media, or alta.",
        "  resp      | YES            | resp:                  | Write nothing after the colon.",
        "  fecha     | YES            | fecha:                 | Write nothing after the colon.",
        "  dep       | YES            | dep:                   | Write nothing after the colon.",
        "  - Do NOT use placeholder strings like 'empty', 'none', 'N/A', or '_' for",
        "    optional fields. Leave them blank (nothing after the colon).",
        "  - For resp, underscores encode spaces: Ana_García → Ana García in the UI.",
        "",
        "SECTION 3 — MULTIPLE RESPONSABLES",
        "  - The resp field holds a single non-whitespace token. To assign multiple",
        "    people, separate their names with a comma and no spaces:",
        "      resp:Ana_García,Luis_Martínez",
        "  - The app stores and displays this as a single string. There is no",
        "    structured multi-owner model; the comma convention is a formatting hint.",
        "  - If you need to record a primary owner plus supporting members, put the",
        "    primary owner in resp and list the rest in the task notes.",
        "",
        "SECTION 4 — PRIORITY (prio)",
        "  - Only three values are valid: baja, media, alta.",
        "  - Any other value (e.g. crítica, urgente) is silently parsed as media.",
        "  - Do not invent new priority levels.",
        "  - Recommended criteria:",
        "      alta  — blocks other tasks or has a hard external deadline.",
        "      media — normal work; should be done within the phase.",
        "      baja  — nice-to-have; can slip without impacting the milestone.",
        "  - When migrating a plan with no explicit priority, use media as default.",
        "",
        "SECTION 5 — TASK NOTES",
        "  - Notes are optional. They go on the lines immediately below the task line.",
        "  - Each note line must start with EXACTLY two spaces. Three or more spaces",
        "    are stored with the leading extra space(s); one space is not recognised",
        "    as a note and is silently discarded.",
        "  - Blank lines (completely empty) between note lines are preserved.",
        "  - There is no length limit per line or per note block.",
        "  - Markdown syntax (bold, links, inline code, lists) is stored verbatim;",
        "    MarkupPM does not render it, but it round-trips safely.",
        "  - The note block ends at the first line that does NOT start with two spaces",
        "    and is NOT blank: i.e. the next task line (- [), a phase header (##),",
        "    the title line (#), or any non-indented content.",
        "",
        "SECTION 6 — CUSTOM / EXTRA METADATA FIELDS",
        "  - The task metadata comment has a fixed schema:",
        "      <!-- id:X prio:X resp:X fecha:X dep:X -->",
        "    Adding any extra key INSIDE the comment (e.g. dur:2h pct:85) breaks the",
        "    regex match and causes the entire task line to be silently dropped.",
        "  - DO NOT add fields to the metadata comment.",
        "  - Store all additional metadata in the task notes using a consistent style:",
        "      dur: 2h",
        "      pct: 85",
        "      tags: urgente, backend",
        "      sprint: S-14",
        "      url: https://example.com/ticket/42",
        "  - There are no reserved note-field names; use any key you need.",
        "",
        "SECTION 7 — SUBTASKS AND HIERARCHY",
        "  - Subtasks are NOT supported as a first-class structure.",
        "    An indented '  - [ ] subtask' is parsed as a note line, not a task.",
        "  - To model logical hierarchy, use one of these patterns:",
        "      a) Break the parent into multiple flat tasks and link them with dep:",
        "         The subtasks become tasks whose dep points to the parent task.",
        "      b) List the sub-steps as numbered note lines under the parent task.",
        "  - Use dep: to make execution order explicit when strict sequencing matters.",
        "",
        "SECTION 8 — TASK ORDER WITHIN A PHASE",
        "  - The parser preserves file order exactly. The serializer writes tasks in",
        "    model order (same as file order after a round-trip).",
        "  - The UI displays tasks in file order; it does not reorder by priority or date.",
        "  - An AI may reorder tasks within a phase without breaking parsing or data.",
        "    Reordering is safe as long as dep: references remain valid.",
        "",
        "SECTION 9 — PHASE STATUS",
        "  - The phase-id comment carries only the id: <!-- phase-id: {id} -->",
        "    There is no status attribute on phases.",
        "  - A phase is not automatically closed when all its tasks reach [x].",
        "    Phase completion is a visual/logical inference in the UI.",
        "  - There is no collapse or archive marker in the file format.",
        "",
        "SECTION 10 — NON-TASK CONTENT WITHIN PHASES",
        "  - Content between tasks that is not indented (paragraphs, ### headers,",
        "    horizontal rules, tables, etc.) is silently discarded by the parser.",
        "  - Do not rely on non-task markdown within a phase being preserved.",
        "  - If you need to attach context to a phase, use notes on a dedicated",
        "    placeholder task (e.g. '- [ ] [Contexto de fase] ...').",
        "",
        "SECTION 11 — CONTENT OUTSIDE PHASES",
        "  - Text between the # title and the first ## phase is silently discarded.",
        "  - Text after the last phase is silently discarded.",
        "  - A '## Changelog' or '## Glosario' line IS parsed as a phase with that",
        "    name (and zero tasks), which may create an unwanted empty phase in the UI.",
        "  - There is no safe zone for free-form content outside of phases.",
        "    Workaround: keep changelogs and appendices in a separate file.",
        "",
        "SECTION 12 — FORMAT LIMITS",
        "  - There are no hardcoded limits on tasks per phase, phases per project,",
        "    dependencies per task, or total file size.",
        "  - No known performance degradation thresholds have been documented.",
        "    As a practical guideline, files with hundreds of tasks parse instantly.",
        "",
        "SECTION 13 — ENCODING AND SPECIAL CHARACTERS",
        "  - Full Unicode is supported in task names, phase names, responsable values,",
        "    and notes (accents, eñes, CJK characters, emoji).",
        "  - Characters safe in task names: : ( ) \" ' / \\ [ ] | — all preserved.",
        "  - Characters that MUST be escaped in task names (handled automatically by",
        "    the serializer): the sequences '<!--' and '-->' are rewritten to",
        "    '&#x3C;!--' and '--&#x3E;' to prevent comment boundary confusion.",
        "  - In resp and id fields, spaces are encoded as underscores. The characters",
        "    '<' and '>' are stripped from resp by the serializer.",
        "  - Do not embed raw '<!--' or '-->' inside task names or note lines;",
        "    use the escaped forms if you need to write them literally.",
        "",
        "SECTION 14 — CHANGELOG AND HISTORY",
        "  - There is no native changelog section in the format.",
        "  - The app does not maintain an internal history of changes.",
        "  - As noted in Section 11, appending '## Changelog' creates an unwanted",
        "    empty phase. Keep changelogs in a separate Markdown file.",
        "",
        "SECTION 15 — MIGRATING FROM EXTERNAL SYSTEMS",
        "  - Preserve original IDs from the source system (see Section 1).",
        "  - Map source states to MarkupPM tokens:",
        "      To do / Backlog       → [ ]",
        "      In progress / Active  → [~]",
        "      Done / Closed         → [x]",
        "  - Map source priority to baja / media / alta (use media as default).",
        "  - Record the migration source in a note line, e.g.:",
        "      migrado desde: Jira PROJ-42",
        "  - If the source has no phase concept, group tasks into logical phases",
        "    (e.g. by epic, sprint, or functional area).",
        "  - If the source has fields with no MarkupPM equivalent (sprint, story points,",
        "    component), store them as key: value note lines (see Section 6).",
        "",
        "SECTION 16 — AI AND HUMAN CO-EDITING",
        "  - The file is designed for both AI generation and direct human editing.",
        "  - This instruction block (<!-- ... -->) is safely ignored by the parser.",
        "    AI agents must NOT modify it.",
        "  - Existing phase-ids and task ids must NEVER be changed by an AI edit,",
        "    as other tasks may reference them via dep: and the app uses them as",
        "    stable keys.",
        "  - Parser tolerance:",
        "      Blank lines between tasks: safe (treated as notes, trimmed away).",
        "      Extra blank lines between phases: safe.",
        "      Note lines with 3+ leading spaces: parsed (leading space kept in note).",
        "      Note lines with 1 leading space: DISCARDED silently.",
        "      Extra keys in the metadata comment: task is DROPPED silently.",
        "      Phase-id comment not on the line immediately after ##: phase gets a",
        "        random id instead (the comment is not associated).",
        "  - Always validate your output against the checklist below before finishing.",
        "",
        "VALIDATION CHECKLIST",
        "  - Exactly one # title line.",
        "  - Every ## phase header is immediately followed by its <!-- phase-id --> comment.",
        "  - Every task line contains all five metadata keys in order: id prio resp fecha dep.",
        "  - No extra keys inside metadata comments.",
        "  - All ids are unique across the file.",
        "  - No raw '<!--' or '-->' sequences inside task names or notes.",
        "  - prio is one of: baja, media, alta.",
        "  - fecha is yyyy-MM-dd or empty.",
        "  - dep is comma-separated ids with no spaces, or empty.",
        "-->"
    ];

    public string Serialize(Proyecto proyecto)
    {
        var sb = new StringBuilder();

        foreach (var headerLine in AiHeaderLines)
            sb.AppendLine(headerLine);

        sb.AppendLine();
        sb.AppendLine($"# {EscapeInline(proyecto.Nombre)}");

        foreach (var fase in proyecto.Fases)
        {
            sb.AppendLine();
            sb.AppendLine($"## {EscapeInline(fase.Nombre)}");
            sb.AppendLine($"<!-- phase-id: {fase.Id} -->");

            foreach (var tarea in fase.Tareas)
            {
                var estado = EstadoToken[(int)tarea.Estado];
                var prio = PrioridadToken[(int)tarea.Prioridad];
                var resp = EscapeAttr(tarea.Responsable);
                var fecha = tarea.Fecha?.ToString("yyyy-MM-dd") ?? "";
                var deps = string.Join(",", tarea.Dependencias);

                sb.AppendLine();
                sb.AppendLine($"- {estado} {EscapeInline(tarea.Nombre)}  <!-- id:{tarea.Id} prio:{prio} resp:{resp} fecha:{fecha} dep:{deps} -->");

                if (!string.IsNullOrWhiteSpace(tarea.Notas))
                {
                    foreach (var line in tarea.Notas.Split('\n'))
                        sb.AppendLine($"  {line.TrimEnd()}");
                }
            }
        }

        return sb.ToString();
    }

    private static string EscapeInline(string s) => s.Replace("<!--", "&#x3C;!--").Replace("-->", "--&#x3E;");
    private static string EscapeAttr(string s) => s.Replace(" ", "_").Replace(">", "").Replace("<", "");
}
